// AUTO-GENERATED by scripts/build-sidecar.ts — do not edit manually.
// Re-run `bun scripts/build-sidecar.ts` to update when migrations change.
import { createHash } from 'node:crypto'
import type { Database } from 'bun:sqlite'

const MIGRATIONS: Array<{ tag: string; sql: string }> = [
  {
    "tag": "0000_initial_schema",
    "sql": "CREATE TABLE `movies` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`title` text NOT NULL,\n\t`original_title` text,\n\t`year` integer,\n\t`overview` text,\n\t`tmdb_id` integer,\n\t`rating` real,\n\t`poster_path` text,\n\t`file_path` text,\n\t`added_at` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE UNIQUE INDEX `movies_tmdb_id_unique` ON `movies` (`tmdb_id`);"
  },
  {
    "tag": "0001_add_api_sources",
    "sql": "CREATE TABLE `api_sources` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`name` text NOT NULL,\n\t`url` text NOT NULL,\n\t`needs_configuration` integer DEFAULT false NOT NULL,\n\t`configuration` text\n);\n"
  },
  {
    "tag": "0002_add_scan_folders",
    "sql": "CREATE TABLE `scan_folders` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`path` text NOT NULL,\n\t`added_at` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE UNIQUE INDEX `scan_folders_path_unique` ON `scan_folders` (`path`);\n"
  },
  {
    "tag": "0003_add_movie_drafts",
    "sql": "CREATE TABLE `movie_drafts` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`file_path` text NOT NULL,\n\t`parsed_title` text,\n\t`parsed_year` integer,\n\t`saved_at` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE UNIQUE INDEX `movie_drafts_file_path_unique` ON `movie_drafts` (`file_path`);"
  },
  {
    "tag": "0004_add_movies_watched",
    "sql": "ALTER TABLE `movies` ADD `watched` integer NOT NULL DEFAULT false;\n"
  },
  {
    "tag": "0005_add_movies_watched_at",
    "sql": "ALTER TABLE `movies` ADD `watched_at` integer;"
  }
]

/**
 * Fallback migrator for compiled binaries that can't find the drizzle/ folder.
 * Uses the same hash format as Drizzle ORM so it's compatible with databases
 * previously set up via `bun run migrate`.
 */
export function runEmbeddedMigrations(sqlite: Database): void {
  sqlite.exec(`CREATE TABLE IF NOT EXISTS "__drizzle_migrations" (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    hash text NOT NULL,
    created_at numeric
  )`)

  const applied = sqlite.query<{ hash: string }, []>(
    'SELECT hash FROM "__drizzle_migrations"'
  ).all()
  const appliedHashes = new Set(applied.map(r => r.hash))

  for (const { tag, sql } of MIGRATIONS) {
    const hash = createHash('sha256').update(sql).digest('hex')
    if (appliedHashes.has(hash)) continue

    // Drizzle splits on statement-breakpoint when executing
    for (const stmt of sql.split('--> statement-breakpoint')) {
      const trimmed = stmt.trim()
      if (trimmed) sqlite.exec(trimmed)
    }

    sqlite.run(
      'INSERT INTO "__drizzle_migrations" (hash, created_at) VALUES (?, ?)',
      [hash, Date.now()]
    )
    console.log(`Applied migration: ${tag}`)
  }
}
