import { execSync } from 'node:child_process'
import { mkdirSync, cpSync, existsSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const binDir = join('apps', 'desktop', 'src-tauri', 'binaries')
mkdirSync(binDir, { recursive: true })

// ─── Step 1: Embed migrations as inline strings ────────────────────────────
// Must run BEFORE `bun build --compile` so the generated TS gets bundled in.
const drizzleSrc = join('apps', 'api', 'drizzle')
if (!existsSync(drizzleSrc)) {
  console.error('ERROR: apps/api/drizzle not found. Run "bun run generate" first.')
  process.exit(1)
}

const journal = JSON.parse(
  readFileSync(join(drizzleSrc, 'meta', '_journal.json'), 'utf-8')
) as { entries: Array<{ tag: string }> }

const migrations = journal.entries.map(({ tag }) => ({
  tag,
  sql: readFileSync(join(drizzleSrc, `${tag}.sql`), 'utf-8'),
}))

const embeddedPath = join('apps', 'api', 'src', 'db', 'embedded-migrations.ts')
writeFileSync(embeddedPath, `// AUTO-GENERATED by scripts/build-sidecar.ts — do not edit manually.
// Re-run \`bun scripts/build-sidecar.ts\` to update when migrations change.
import { createHash } from 'node:crypto'
import type { Database } from 'bun:sqlite'

const MIGRATIONS: Array<{ tag: string; sql: string }> = ${JSON.stringify(migrations, null, 2)}

/**
 * Fallback migrator for compiled binaries that can't find the drizzle/ folder.
 * Uses the same hash format as Drizzle ORM so it's compatible with databases
 * previously set up via \`bun run migrate\`.
 */
export function runEmbeddedMigrations(sqlite: Database): void {
  sqlite.exec(\`CREATE TABLE IF NOT EXISTS "__drizzle_migrations" (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    hash text NOT NULL,
    created_at numeric
  )\`)

  const applied = sqlite.query<{ hash: string }, []>(
    'SELECT hash FROM "__drizzle_migrations"'
  ).all()
  const appliedHashes = new Set(applied.map(r => r.hash))

  for (const { tag, sql } of MIGRATIONS) {
    const hash = createHash('sha256').update(sql).digest('hex')
    if (appliedHashes.has(hash)) continue

    // Drizzle splits on statement-breakpoint when executing
    for (const stmt of sql.split('--> statement-breakpoint')) {
      const trimmed = stmt.trim()
      if (trimmed) sqlite.exec(trimmed)
    }

    sqlite.run(
      'INSERT INTO "__drizzle_migrations" (hash, created_at) VALUES (?, ?)',
      [hash, Date.now()]
    )
    console.log(\`Applied migration: \${tag}\`)
  }
}
`)
console.log(`Generated embedded migrations → ${embeddedPath}`)

// ─── Step 2: Compile API binary ────────────────────────────────────────────
const ext = process.platform === 'win32' ? '.exe' : ''
const outfile = join(binDir, `rmdb-api${ext}`)

console.log(`Building API binary → ${outfile}`)
execSync(
  `bun build --compile --external=sharp apps/api/src/index.ts --outfile "${outfile}"`,
  { stdio: 'inherit' }
)

// ─── Step 3: Copy runtime dependencies ────────────────────────────────────
const sharpSrc =
  existsSync(join('apps', 'api', 'node_modules', 'sharp'))
    ? join('apps', 'api', 'node_modules', 'sharp')
    : join('node_modules', 'sharp')
const sharpDst = join(binDir, 'node_modules', 'sharp')
if (existsSync(sharpSrc)) {
  console.log(`Copying sharp native module → ${sharpDst}`)
  cpSync(sharpSrc, sharpDst, { recursive: true })
} else {
  console.error('ERROR: node_modules/sharp not found. Run bun install first.')
  process.exit(1)
}

// Copy drizzle folder alongside the binary (preferred path; embedded SQL is the fallback).
const drizzleDst = join(binDir, 'drizzle')
console.log(`Copying migrations → ${drizzleDst}`)
cpSync(drizzleSrc, drizzleDst, { recursive: true })

console.log(`Done`)
